permalink: /:title 
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
highlighter:  rouge/pygments
markdown: kramdown
paginate: 10
author :
  name : KenzieChen
  email : 595612343@qq.com
  github : KenzieChen

production_url : http://KenzieChen.github.io

comments :
  provider : disqus
  disqus :
    short_name : kenziechen-blog

